name: filter commit nessage
on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: fetch repo
        uses: actions/checkout@v2
          with:
            fetch-depth: 2

      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get commit message
        run: |
           git log -n 2
           #echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run : echo $commitmsg

      - name: step1
        if: contains( env.commitmsg , 'ja' )
        run: echo hello
